#!/usr/bin/env bash
# Allows to run a individual tests
# Usage:
#   ./run_individual_tests <test-file>...
# Example:
#   ./run_individual_tests runnable/template2962.d fail_compilation/fail282.d

# See the Makefile for all available test targets

set -euo pipefail

if [ -z ${1:-} ] ; then
	cat >&2 << EOF
./run_individual_tests <test-file>...

Examples:

    ./run_individual_tests runnable/template2962.d
    ./run_individual_tests runnable/template2962.d fail_compilation/fail282.d
EOF
	exit
fi

# all test files to be run
files=()

# normalize path to each test file
for arg in "$@" ; do
	file="$arg"
	normalizedDir=$(cd "$(dirname "$file")" && pwd)
	files+=("test_results/$(basename "$normalizedDir" )/$(basename "$file").out")
done

# allows the script to be called from anywhere
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
${MAKE:-make} "${files[@]}"
