.TH DUMBOBJ 1 "2006-03-12" "Digital Mars" "Digital Mars D"
.SH name
dumpobj \- Digital Mars Object File (.obj) Dumper

.SH SYNOPSIS
.B dumpobj
[-p]
.I filename[.obj]

.SH OPTIONS

.IP -p
pretty-print

.SH AUTHOR
Copyright (C) Digital Mars 1985-2003.  All Rights Reserved.

.SH "SEE ALSO"
.BR dmd (1)
