.TH DMD.CONF 5 "2006-03-12" "Digital Mars" "Digital Mars D"
.SH NAME
dmd.conf \- configuration file for
.BR dmd (1)

.SH SYNOPSIS
.I /etc/dmd.conf

.SH DESCRIPTION
dmd will look for the initialization file
.I dmd.conf
in the following directories:
.IP 1. 3
The current working directory.
.IP 2. 3
\fB$HOME\fR
.IP 3. 3
The directory containing the \fBdmd\fR executable.
.IP 4. 3
\fI/etc\fR
.PP
If found, environment variable settings in the file will override any
existing settings.
.PP

This is handy to make dmd independent of programs with
conflicting use of environment variables.

.SH SYNTAX
Environment variables follow the [Environment] section heading, in
name=value or name?=value pairs. Comments are lines that start with ;.
Variable names are always converted to uppercase, so if you use
name=value, actually the variable with name NAME will be written.  If
the name?=value syntax is used, the variable with NAME will only be
written if it was defined before (in that case the original value is
preserved).
.PP

.SH EXAMPLE
.PD 0.5
; dmd.conf file for dmd
.LP
; Names enclosed by %% are searched for in the existing environment
.LP
; and inserted. The special name %@P% is replaced with the path
.LP
; to this file.
.LP
[Environment]
.LP
DFLAGS="-I%@P%/../src/phobos"
.PD

.SH FILES
.I /etc/dmd.conf

.SH "SEE ALSO"
.BR dmd (1)
.BR rdmd (1)
