#!/usr/bin/env bash

source tools/common_funcs.sh

grep --text -v "Generated by Ddoc from" ${OUTPUT_BASE}.html > ${OUTPUT_BASE}.html.2
diff -up --strip-trailing-cr ${EXTRA_FILES}/${TEST_NAME}.html ${OUTPUT_BASE}.html.2

rm_retry ${OUTPUT_BASE}.html{,.2}
