=== compilable/vcg-ast-ctfeonly.d.cg
module vcg_ast_ctfeonly;
import object;
int twice(int x)
{
	return x * 2;
}
int ctfeOnly(T)(T x)
{
	return helper!T
	{
	}
	(x);
}
int helper(T)(T x)
{
	return twice(x) + 1;
}
int atRuntime(T)(T x)
{
	return twice(x);
}
enum int e = 3;
int main()
{
	return vcg_ast_ctfeonly.atRuntime!int(3);
}
mixin _d_cmain!();
{
	extern (C)
	{
		extern(C) int _d_run_main(int argc, char** argv, void* mainFunc);
		extern(C) int _Dmain(char[][] args);
		extern(C) int main(int argc, char** argv)
		{
			return vcg_ast_ctfeonly._d_cmain!()._d_run_main(argc, argv, & _Dmain);
		}
		version (Solaris)
		{
			extern(C) int _main(int argc, char** argv)
			{
				return main(argc, argv);
			}
		}
	}
}
atRuntime!int
{
	@system int atRuntime(int x)
	{
		return vcg_ast_ctfeonly.twice(x);
	}

}
