version: 2.1
jobs:
  build:
    working_directory: ~/dmd # the Phobos Makefile expects this dir name, not Circle's default `~/project`
    machine:
      image: ubuntu-2604:current
    resource_class: large.gen3
    steps:
      - checkout
      - run:
          command: ./.circleci/run.sh install-deps
          name: Install dependencies
      - run:
          # needs to be a separate step, s.t. `run.sh` gets updated too
          command: ./.circleci/run.sh setup-repos
          name: Merge with upstream + clone Phobos
      - run:
          command: ./.circleci/run.sh all
          name: Run all
workflows:
  all:
    jobs:
      - build
