bytes allocated, allocations, type, function, file:line
            160	              1	float profilegc.main src/profilegc.d:18
            160	              1	int profilegc.main src/profilegc.d:15
             64	              1	double[] profilegc.main src/profilegc.d:56
             48	              1	float[] profilegc.main src/profilegc.d:42
             48	              1	int[] profilegc.main src/profilegc.d:41
             32	              1	C profilegc.main src/profilegc.d:12
             32	              1	void[] profilegc.main src/profilegc.d:55
             16	              1	char[] profilegc.main src/profilegc.d:34
             16	              1	char[] profilegc.main src/profilegc.d:36
             16	              1	closure profilegc.main.foo src/profilegc.d:45
             16	              1	float profilegc.main src/profilegc.d:16
             16	              1	float profilegc.main src/profilegc.d:17
             16	              1	int profilegc.main src/profilegc.d:13
             16	              1	int profilegc.main src/profilegc.d:14
             16	              1	int[] profilegc.main src/profilegc.d:22
             16	              1	int[] profilegc.main src/profilegc.d:37
             16	              1	wchar[] profilegc.main src/profilegc.d:35
