/**
 * D bindings for WASI preview2.
 *
 * These bindings are generated by running
 *  $(LINK2 https://github.com/bytecodealliance/wit-bindgen/pull/1561, a fork of `wit-bindgen`)
 * against the WASIp2 WIT definitions (see standards link).
 *
 * Standards: $(LINK2 https://github.com/WebAssembly/WASI/tree/wasi-0.2/, WebAssembly System Interface (WASI) 0.2)
 */
module core.sys.wasi.p2;

version (WASIp2):

// All of it
public import core.sys.wasi.p2.cli.imports;
