/*
These tests are for the @__ctfe attribute, specifically the errors generated by the frontend.
TEST_OUTPUT:
---
fail_compilation/test_ctfe_attribute_frontend.d(21): Error: class and interface methods cannot be marked as ctfe only due to inheritance
fail_compilation/test_ctfe_attribute_frontend.d(21):        perhaps mark `act` as final so it cannot be overridden
fail_compilation/test_ctfe_attribute_frontend.d(24): Error: class and interface methods cannot be marked as ctfe only due to inheritance
fail_compilation/test_ctfe_attribute_frontend.d(24):        perhaps mark `method` as final so it cannot be overridden
---
*/

void main() {
}

class Foo {
    void act() {
    }
}

class Bar : Foo {
    override void act() @__ctfe {
    }

    void method() @__ctfe {
    }

    private void nonthing() @__ctfe {
    }
}
