/*
These tests are for the @__ctfe attribute, specifically the errors generated by the glue code.
TEST_OUTPUT:
---
fail_compilation/test_ctfe_attribute_glue.d(15): Error: function `test_ctfe_attribute_glue.add` is `@__ctfe` and cannot be used at runtime
fail_compilation/test_ctfe_attribute_glue.d(17): Error: function `test_ctfe_attribute_glue.checkMulti` is `@__ctfe` and cannot be used at runtime
fail_compilation/test_ctfe_attribute_glue.d(20): Error: function `test_ctfe_attribute_glue.add` is `@__ctfe` and cannot be used at runtime
---
*/

int add(int a) @__ctfe => a + 2;

void main() {
    // Error: calling @__ctfe function at runtime
    int x = add(9);

    int y = checkMulti(6);

    // Error: taking address of @__ctfe function at runtime
    auto fp = &add;
}

@__ctfe:

int checkMulti(int) {
    return 0;
}
