name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'dashboard.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository with full history.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Prepare the deploy folder by copying dashboard.html to _temp/index.html.
      - name: Prepare deploy folder
        run: |
          mkdir -p _temp
          dashboard_path=$(find . -name "dashboard.html" -type f | head -1)
          if [ -n "$dashboard_path" ]; then
            echo "Found dashboard at: $dashboard_path"
            cp "$dashboard_path" _temp/index.html
          else
            echo "ERROR: dashboard.html not found in repository"
            exit 1
          fi

      # 3. Deploy the _temp folder to the gh-pages branch using peaceiris/actions-gh-pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _temp
          publish_branch: gh-pages
