name: Update GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'dashboard.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Git identity for subsequent git commands
      - name: Setup git identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      # Prepare the folder that will be deployed (copy dashboard.html to _temp/index.html)
      - name: Prepare deploy folder
        run: |
          mkdir -p _temp
          dashboard_path=$(find . -name "dashboard.html" -type f | head -1)
          if [ -n "$dashboard_path" ]; then
            echo "Found dashboard at: $dashboard_path"
            cp "$dashboard_path" _temp/index.html
          else
            echo "ERROR: dashboard.html not found in repository"
            exit 1
          fi

      # Ensure the gh-pages branch is initialized and has at least one commit.
      - name: Ensure gh-pages branch is initialized
        run: |
          # Try to fetch the remote gh-pages branch (ignore error if it doesn’t exist)
          git fetch origin gh-pages || true
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            echo "gh-pages branch exists, checking commit history..."
            git checkout gh-pages
            commit_count=$(git rev-list --count HEAD || echo 0)
            if [ "$commit_count" -eq 0 ]; then
              echo "gh-pages branch is empty. Creating initial commit..."
              git rm -rf . || true
              echo "# GitHub Pages" > README.md
              git add README.md
              git commit -m "Initialize gh-pages branch"
              git push origin gh-pages
            fi
            git checkout master
          else
            echo "gh-pages branch does not exist, creating it..."
            git checkout --orphan gh-pages
            git rm -rf .
            echo "# GitHub Pages" > README.md
            git add README.md
            git commit -m "Initialize gh-pages branch"
            git push origin gh-pages
            git checkout master
          fi

      # Deploy the _temp folder to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages        # The target branch for deployment
          folder: _temp           # The folder containing your deployable content
          clean: false
          token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          attempt-limit: 3
