name: Update GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'dashboard.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Check out the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Debug output (optional)
      - name: Debug repository structure
        run: |
          echo "Repository root contents:"
          ls -la
          echo "Current branch: $(git branch --show-current)"

      # Set up Git identity for any git commands that follow
      - name: Setup git identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      # Prepare the folder that will be deployed
      - name: Prepare deploy folder
        run: |
          mkdir -p _temp
          dashboard_path=$(find . -name "dashboard.html" -type f | head -1)
          if [ -n "$dashboard_path" ]; then
            echo "Found dashboard at: $dashboard_path"
            cp "$dashboard_path" _temp/index.html
          else
            echo "ERROR: dashboard.html not found in repository"
            exit 1
          fi

      # Initialize the gh-pages branch if it doesn't exist to avoid orphan branch issues
      - name: Initialize gh-pages branch if not exists
        run: |
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            echo "Creating gh-pages branch..."
            git checkout --orphan gh-pages
            git rm -rf .
            echo "# GitHub Pages" > README.md
            git add README.md
            git commit -m "Initialize gh-pages branch"
            git push origin gh-pages
            git checkout master
          else
            echo "gh-pages branch already exists"
          fi

      # Deploy the contents of _temp to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages    # The target branch for deployment
          folder: _temp       # The folder containing the deployable site (your dashboard)
